trigger:
- master
- develop
- azure-pipelines

variables:
  sdk_version: 3.0.100-preview6-012264
  projectFolder: Aktiv.RtAdmin
  mainProjectPath: ./$(projectFolder)/$(projectFolder).csproj

jobs:
- job: 'osx'
  pool:
    vmImage: macOS-10.13
  steps:
  - checkout: self
    submodules: true

  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core sdk $(sdk_version)'
    inputs:
      version: $(sdk_version)

  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: custom
      projects: $(mainProjectPath)
      custom: restore
      arguments: '-r osx-x64'
  
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build Release'
    inputs:
      projects: $(mainProjectPath)
      arguments: '-r osx-x64 -c Release'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish'
    inputs:
      command: publish
      projects: $(mainProjectPath)
      arguments: '-c Release -r osx-x64 --self-contained -o $(Build.StagingDirectory)'
      zipAfterPublish: false